const actionType = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ADD_CLASS: "ADD_CLASS",
  UPDATE_CLASS_LIST: " UPDATE_CLASS_LIST",
  UPDATE_CLASS_DETAILS: "UPDATE_CLASS_DETAILS",
  UPDATE_TOTAL_GRADE_COL: "UPDATE_TOTAL_GRADE_COL",
  COUNT_RERENDER: "COUNT_RERENDER",
  UPDATE_GRADE_STRUCT: "UPDATE_GRADE_STRUCT"
}

export default actionType
