const actionType = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ADD_CLASS: "ADD_CLASS",
  UPDATE_CLASS_LIST: " UPDATE_CLASS_LIST",
  UPDATE_CLASS_DETAILS: "UPDATE_CLASS_DETAILS",
}

export default actionType
